apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-container
        image: kirthiksubbiah/java-microservice:latest
        ports:
        - containerPort: 8080
